<#-- $This file is distributed under the terms of the license in /doc/license.txt$ -->
<#--Number of labels present-->
<#if !labelCount??>
    <#assign labelCount = 0 >
</#if>
<#--Number of available locales-->
<#if !localesCount??>
	<#assign localesCount = 1>
</#if>
<#--Number of distinct languages represented, with no language tag counting as a language, across labels-->
<#if !languageCount??>
	<#assign languageCount = 1>
</#if>	

<#-- Default individual profile page template -->
<#--@dumpAll /-->

<section id="individual-intro" class="vcard" role="region">
    <section id="share-contact" role="region">
        <#-- Image -->
        <#assign individualImage>
        <@p.image individual=individual
            propertyGroups=propertyGroups
            namespaces=namespaces
            editable=editable
            showPlaceholder="with_add_link" />
        </#assign>

        <#if ( individualImage?contains('<img class="individual-photo"') )>
            <#assign infoClass = 'class="withThumb"'/>
        </#if>
        <div id="photo-wrapper">${individualImage}</div>
    </section>
    <!-- start section individual-info -->
    <section id="individual-info" ${infoClass!} role="region">
        <#include "individual-adminPanel.ftl">
        
        <header>
            <#if relatedSubject??>
                <h2>${relatedSubject.relatingPredicateDomainPublic} for ${relatedSubject.name}</h2>
                <p><a href="${relatedSubject.url}" title="${i18n().return_to(relatedSubject.name)}">&larr; ${i18n().return_to(relatedSubject.name)}</a></p>                
            <#else>                
                <h1 class="fn">
                    <#-- Label -->
                    <@p.label individual editable labelCount localesCount languageCount/>

                    <#--  Most-specific types -->
                    <@p.mostSpecificTypes individual />
                    <span id="iconControlsVitro"><img id="uriIcon" title="${individual.uri}" class="middle" src="${urls.images}/individual/uriIcon.gif" alt="uri icon"/></span>
                </h1>
            </#if>
        </header>

        <#include "individual-researchAreas.ftl">
        <#include "individual-industrySectors.ftl">
                
    <#if individualProductExtension??>
        ${individualProductExtension}
    <#else>
            </section> <!-- individual-info -->
        </section> <!-- individual-intro -->
    </#if>

<#assign nameForOtherGroup = "${i18n().other}"> 

<!-- Property group menu or tabs -->
<#-- 
    With release 1.6 there are now two types of property group displays: the original property group
     menu and the horizontal tab display, which is the default. If you prefer to use the property
     group menu, simply substitute the include statement below with the one that appears after this
     comment section. 
-->     
     <#include "individual-property-group-menus.ftl">


<#assign rdfUrl = individual.rdfUrl>

<#if rdfUrl??>
    <script>
        var individualRdfUrl = '${rdfUrl}';
    </script>
</#if>
<script>
    var i18nStringsUriRdf = {
        shareProfileUri: '${i18n().share_profile_uri}',
        viewRDFProfile: '${i18n().view_profile_in_rdf}',
        closeString: '${i18n().close}'
    };
</script>

${stylesheets.add('<link rel="stylesheet" href="${urls.base}/css/individual/individual.css" />')}

${headScripts.add('<script type="text/javascript" src="${urls.base}/js/jquery_plugins/qtip/jquery.qtip-1.0.0-rc3.min.js"></script>',
                  '<script type="text/javascript" src="${urls.base}/js/tiny_mce/tiny_mce.js"></script>')}

${scripts.add('<script type="text/javascript" src="${urls.base}/js/imageUpload/imageUploadUtils.js"></script>',
              '<script type="text/javascript" src="${urls.base}/js/individual/individualUriRdf.js"></script>')}

<script type="text/javascript">
    i18n_confirmDelete = "${i18n().confirm_delete}"
</script>


<#-- THIS IS BAD. PLEASE DO NOT USE THIS PATTERN ANYWHERE ELSE -->
<script type="text/javascript">

    // Remove extra element generated by VIVO since it isn't formatted correctly.
    $('article').find('h3#has_honored_member').each(function(i, e){ if (e.innerText == "honored faculty member"){ e.parentNode.remove() } });


    // Iterate through hidden elements generated in propStatement-awardInOrganization.ftl to repaint DOM.
    $("#has_honored_member-Person-List li").each(function(index, elem) {

        var info = $(elem).find('span');
        var type_ = info.attr('data-award-type');
        var url_ = info.attr('data-url');
        var award_name = info.attr('data-award-name');
        var person_name = info.attr('data-person-name');
        var date_time = info.attr('data-date').substring(0,4);

        // If a DOM element doesn't exist for award yet, create one.
        if ($('#'+type_).length == 0) {
            $('#has_honored_member-Person-List').append('<li class="subclass"><h3>'+award_name+'</h3><ul class="subclass-property-list" id="'+type_+'"></ul></li>');
        }

        // Add list element for each entry.
        var li_content = '<li><a href="'+url_+'">'+person_name+'</a>&nbsp;<span class="listDateTime">'+date_time+'</span></li>';
        $('ul#'+type_).append(li_content);

        // Remove our invisible span elements from the ftl file.
        $(elem).remove();
    });

</script>
